languageCode: en
title: Protocol Labs Research
summaryLength: 30
googleAnalytics: UA-96910779-16
BaseURL: "https://research.protocol.ai"
relativeURLs: true
copyright: "Â© Protocol Labs, Inc. Except as noted, content licensed CC-BY 3.0."
taxonomies:
  author: authors
  category: categories
  publication_type: publication_types
  tag: tags
  research_area: research_areas
  research_group: research_groups
params:
  DateForm: 2006.1.2
  Avatar: /images/pl_research_card.png
  Logo: /images/pl_research_logo.png
  Author: "Protocol Labs Research"
  Description: "Protocol Labs Research explores the future of decentralization and examines the infrastructure limiting what you can do with technology."
  Locale: "en_US"
  TwitterUser: "@protocollabs"
permalinks:
  talks: /research/talks/:title/
  publications: /research/publications/:title/
  research_areas: /research/areas/:title/
  research_groups: /research/groups/:title/
  posts: /blog/:year/:title/
markup:
  goldmark:
    renderer:
      unsafe: true
